"""Initial migration.

Revision ID: eb77d6141770
Revises: 
Create Date: 2026-02-22 02:23:48.308168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb77d6141770'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roast', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coffees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('presentation', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('bean_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bean_id'], ['beans.id'], name=op.f('fk_coffees_bean_id_beans')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_coffees_store_id_stores')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_coffees_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coffees')
    op.drop_table('users')
    op.drop_table('stores')
    op.drop_table('beans')
    # ### end Alembic commands ###
